name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      # Step 1: Pull your code into the runner
      - name: Checkout code
        uses: actions/checkout@v4

      # 2️⃣ Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        
       # Step 3: Build Docker image
      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/simple-ci-app:latest .

      # 4️⃣ Push image to Docker Hub
      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/simple-ci-app:latest



       # 5️⃣ Deploy on Azure VM
      - name: Deploy to Azure VM
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.AZURE_HOST }}
          username: ${{ secrets.AZURE_USER }}
          key: ${{ secrets.AZURE_SSH_KEY }}
          script: |
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/simple-ci-app:latest
            docker stop simple-ci-app || true
            docker rm simple-ci-app || true
            docker run -d \
              --name simple-ci-app \
              -p 3000:3000 \
              ${{ secrets.DOCKERHUB_USERNAME }}/simple-ci-app:latest
              








        
